// this was generated by app.quicktype.io, there's lots of tools to map results but this one was quick to implement

import 'dart:convert';

GetBalanceForAccountResponse getBalanceForAccountResponseFromJson(String str) =>
    GetBalanceForAccountResponse.fromJson(json.decode(str));

String getBalanceForAccountResponseToJson(GetBalanceForAccountResponse data) => json.encode(data.toJson());

class GetBalanceForAccountResponse {
  GetBalanceForAccountResponse({
    required this.method,
    required this.result,
    required this.jsonrpc,
    required this.id,
  });

  final String method;
  final Result result;
  final String jsonrpc;
  final int id;

  factory GetBalanceForAccountResponse.fromJson(Map<String, dynamic> json) => GetBalanceForAccountResponse(
        method: json["method"],
        result: Result.fromJson(json["result"]),
        jsonrpc: json["jsonrpc"],
        id: json["id"],
      );

  Map<String, dynamic> toJson() => {
        "method": method,
        "result": result.toJson(),
        "jsonrpc": jsonrpc,
        "id": id,
      };
}

class Result {
  Result({
    required this.balance,
  });

  final Balance balance;

  factory Result.fromJson(Map<String, dynamic> json) => Result(
        balance: Balance.fromJson(json["balance"]),
      );

  Map<String, dynamic> toJson() => {
        "balance": balance.toJson(),
      };
}

class Balance {
  Balance({
    required this.object,
    required this.networkBlockHeight,
    required this.localBlockHeight,
    required this.accountBlockHeight,
    required this.isSynced,
    required this.unspentPmob,
    required this.pendingPmob,
    required this.spentPmob,
    required this.secretedPmob,
    required this.orphanedPmob,
  });

  final String object;
  final String networkBlockHeight;
  final String localBlockHeight;
  final String accountBlockHeight;
  final bool isSynced;
  final String unspentPmob;
  final String pendingPmob;
  final String spentPmob;
  final String secretedPmob;
  final String orphanedPmob;

  factory Balance.fromJson(Map<String, dynamic> json) => Balance(
        object: json["object"],
        networkBlockHeight: json["network_block_height"],
        localBlockHeight: json["local_block_height"],
        accountBlockHeight: json["account_block_height"],
        isSynced: json["is_synced"],
        unspentPmob: json["unspent_pmob"],
        pendingPmob: json["pending_pmob"],
        spentPmob: json["spent_pmob"],
        secretedPmob: json["secreted_pmob"],
        orphanedPmob: json["orphaned_pmob"],
      );

  Map<String, dynamic> toJson() => {
        "object": object,
        "network_block_height": networkBlockHeight,
        "local_block_height": localBlockHeight,
        "account_block_height": accountBlockHeight,
        "is_synced": isSynced,
        "unspent_pmob": unspentPmob,
        "pending_pmob": pendingPmob,
        "spent_pmob": spentPmob,
        "secreted_pmob": secretedPmob,
        "orphaned_pmob": orphanedPmob,
      };
}
